version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${ARLAS_PERSISTENCE_DB_USER:-pg-user}
      POSTGRES_PASSWORD: ${ARLAS_PERSISTENCE_DB_PASSWORD:-iAMs00perSecrEET}
      POSTGRES_DB: arlas_persistence
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    volumes:
      - ${ARLAS_PERSISTENCE_CREATESQL_FILE:-/opt/app/pgCreateTable.sql}:/docker-entrypoint-initdb.d/createTable.sql:ro
    healthcheck:
      test: "pg_isready -d arlas_persistence"
      interval: 10s
      timeout: 3s
      retries: 30

  arlas-persistence-server:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only}
    image: gisaia/arlas-persistence-server:${ARLAS_PERSISTENCE_SERVER_VERSION:-latest}
    container_name: arlas-persistence-server
    restart: always
    environment:
      - ARLAS_PERSISTENCE_HOST="${ARLAS_PERSISTENCE_HOST:-localhost}"
      - ARLAS_PERSISTENCE_PORT="${ARLAS_PERSISTENCE_PORT:-9997}"
      - ARLAS_PERSISTENCE_PREFIX="${ARLAS_PERSISTENCE_PREFIX:-/arlas_persistence_server}"
      - ARLAS_PERSISTENCE_APP_PATH="${ARLAS_PERSISTENCE_APP_PATH:-/}"
      - ARLAS_AUTH_POLICY_CLASS="${ARLAS_AUTH_POLICY_CLASS:-io.arlas.filter.impl.NoPolicyEnforcer}"
      - ARLAS_AUTH_PERMISSION_URL="${ARLAS_AUTH_PERMISSION_URL:-http://arlas-iam-server:9990/arlas_iam_server/permissions}"
      - ARLAS_AUTH_CERT_URL="${ARLAS_AUTH_CERT_URL}"
      - ARLAS_PERSISTENCE_CACHE_FACTORY_CLASS="${ARLAS_PERSISTENCE_CACHE_FACTORY_CLASS:-io.arlas.commons.cache.BaseLocalCacheFactory}"
      - ARLAS_CACHE_TIMEOUT="${ARLAS_CACHE_TIMEOUT:-5}"
      - ARLAS_PERSISTENCE_ENGINE="${ARLAS_PERSISTENCE_ENGINE:-file}"
      - ARLAS_PERSISTENCE_LOCAL_FOLDER="${ARLAS_PERSISTENCE_LOCAL_FOLDER:-/tmp/persist/}"
#      - ARLAS_PERSISTENCE_ENGINE="${ARLAS_PERSISTENCE_ENGINE:-firestore}"
#      - ARLAS_PERSISTENCE_FIRESTORE_COLLECTION="${ARLAS_PERSISTENCE_FIRESTORE_COLLECTION:-user_pref}"
#      - ARLAS_PERSISTENCE_ENGINE="${ARLAS_PERSISTENCE_ENGINE:-hibernate}"
      - ARLAS_PERSISTENCE_HIBERNATE_URL="${ARLAS_PERSISTENCE_HIBERNATE_URL:-jdbc:postgresql://db:5432/arlas_persistence}"
      - ARLAS_PERSISTENCE_HIBERNATE_USER="${ARLAS_PERSISTENCE_HIBERNATE_USER:-pg-user}"
      - ARLAS_PERSISTENCE_HIBERNATE_PASSWORD="${ARLAS_PERSISTENCE_HIBERNATE_PASSWORD:-iAMs00perSecrEET}"
      - ARLAS_PERSISTENCE_HIBERNATE_DRIVER="${ARLAS_PERSISTENCE_HIBERNATE_DRIVER:-org.postgresql.Driver}"
      - ARLAS_PERSISTENCE_HIBERNATE_DIALECT="${ARLAS_PERSISTENCE_HIBERNATE_DIALECT:-org.hibernate.dialect.PostgreSQLDialect}"
      - ARLAS_PERSISTENCE_HIBERNATE_HBM2DDL="${ARLAS_PERSISTENCE_HIBERNATE_HBM2DDL:-update}"
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/app/google-registry.json
    ports:
      - "19997:9997" # !EXPOSE!
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/tmp}:/opt/app/google-registry.json:ro
      - ${ARLAS_PERSISTENCE_LOCAL_FOLDER_HOST:-/tmp/persist/}:${ARLAS_PERSISTENCE_LOCAL_FOLDER:-/tmp/persist/}:rw
    healthcheck:
      test: ["CMD","java","HttpHealthcheck.java","http://localhost:9997/admin/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 3
