version: '3'

services:
  arlas-persistence-server:
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only}
    image: gisaia/arlas-persistence-server:${ARLAS_VERSION:-latest}
    container_name: arlas-persistence-server
    environment:
      - ARLAS_SERVER_PORT="${ARLAS_SERVER_PORT:-9997}"
      - ARLAS_SERVER_PREFIX="${ARLAS_SERVER_PREFIX:-/arlas_persistence_server}"
      - ARLAS_SERVER_APP_PATH="${ARLAS_SERVER_APP_PATH:-/}"
      - ARLAS_AUTH_ENABLED="${ARLAS_AUTH_ENABLED:-false}"
      - ARLAS_PERSISTENCE_KEY_HEADER="${ARLAS_PERSISTENCE_KEY_HEADER:-X-Forwarded-User}"
    ports:
      - 19997:9997
    volumes:
      - ${ARLAS_AUTH_LOCAL_CERT_FILE:-/tmp}:${ARLAS_AUTH_CERT_FILE:-/opt/app/arlas.pem}:ro
    command: ["/opt/app/start.sh"]
