name: Test ARLAS-persistence

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Cache Maven # From https://github.com/actions/cache/blob/main/examples.md
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Warm-up mvn cache
      run: |
        mvn --version
        mvn clean verify
    - name: Prepare tests
      run: |
        sudo sysctl -w vm.max_map_count=262144
        sudo mkdir -p /opt/app
        sudo cp arlas-persistence-tests/src/test/resources/arlas-test.pem /opt/app/
        sudo cp docker/docker-files/pgCreateTable.sql /opt/app/
    - name: Run tests [file engine]
      env:
        # secrets are defined here : https://github.com/organizations/gisaia/settings/secrets/actions
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: scripts/ci/tests-integration-stage.sh --stage="REST_FILE"
    - name: Run tests [hibernate engine]
      env:
        # secrets are defined here : https://github.com/organizations/gisaia/settings/secrets/actions
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: scripts/ci/tests-integration-stage.sh --stage="REST_HIBERNATE"
